Update Node.js version to 22 across project configuration, dependencies and devcontainer
Running lint didn't work until moving the call of pre-commit from the inline dockerfile to the command tag. Most likely a mount timing race condition.
docker compose -f dev.yml run lint
/bin/sh: ./githooks/pre-commit: not found

Checkin failed for yarn tsc --noEmit due to error in
src/pages/api/views/download.ts
src/pages/api/journeyInstances/download.ts
with messages:

src/pages/api/journeyInstances/download.ts(31,5): error TS2322: Type 'NextApiResponse<any>' is not assignable to type 'void'.
src/pages/api/journeyInstances/download.ts(35,5): error TS2322: Type 'NextApiResponse<any>' is not assignable to type 'void'.
src/pages/api/journeyInstances/download.ts(53,5): error TS2322: Type 'NextApiResponse<any>' is not assignable to type 'void'.
src/pages/api/journeyInstances/download.ts(170,5): error TS2322: Type 'NextApiResponse<any>' is not assignable to type 'void'.
src/pages/api/views/download.ts(30,5): error TS2322: Type 'NextApiResponse<any>' is not assignable to type 'void'.
src/pages/api/views/download.ts(34,5): error TS2322: Type 'NextApiResponse<any>' is not assignable to type 'void'.
src/pages/api/views/download.ts(108,5): error TS2322: Type 'NextApiResponse<any>' is not assignable to type 'void'.
error Command failed with exit code 2.

Fixed that by separating to a return void.